pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Sponge Snapshots'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

// This should match the folder name of the project, or else IDEA may complain (see https://youtrack.jetbrains.com/issue/IDEA-317606)
rootProject.name = 'Feathered Friend'
include("common")
include("fabric")
include("forge")

// Local dev dependency (required mod): RPG_Calendar / rpgtimeline
// This allows Gradle to resolve rpgtimeline from source without dropping jars into `forge/run/mods`.
includeBuild("../RPG_Calendar") {
    dependencySubstitution {
        substitute module("org.z2six.rpgtimeline:rpgtimeline-forge-1.20.1") using project(":forge")
    }
}
